// generated by @ng-toolkit/serverless
'use strict';
const server = require('./dist/server');
const functions = require('firebase-functions');
const cors = require('cors')({ origin: true });
const admin = require('firebase-admin');
admin.initializeApp();


const http = functions.https.onRequest((request, response) => {
    if (!request.path) {
        request.url = "/" + request.url;
    }

    return server.app(request, response);
});
const helloWorld = functions.https.onRequest((req, res) => {
    res.json({
        key: 'Hello'
    });
});

const addItem = functions.https.onRequest((req, res) => {
    let items = [];

    const data = admin.database().ref('/users').push(req.body)
    admin.database().ref('/users/' + data.key).on('value', (data) => {
        return res.json({
            _id: data.key,
            data: data
        });
    })
})

const getItem = functions.https.onRequest((req, res) => {
    admin.database().ref('/users').on('value', (data) => {
        return res.json(data);
    })
})


module.exports = {
    http,
    helloWorld,
    addItem, getItem

}